# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.10
_src_path: gh:algorandfoundation/algokit-python-template
author_email: paynedestinne@gmail.com
author_name: D3stinn3
contract_name: voting_machine
deployment_language: python
preset_name: production
project_name: voting_machine

